### ISSUE TITLE
User Story 6: Selecting names and setting filters

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#10]
## Value statement 
As a **user** 
I want to **select guests to summarize their intolerances** 
so that **I have an easy overview of my guests intolerances**. 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/79710919/198571385-5df19bb0-2239-42aa-aac9-5fd960f96758.png)

![Image](https://user-images.githubusercontent.com/79710919/198830768-df43aef3-b787-4b63-857b-9d5ecba68a94.png)

## Acceptance criteria
- [x] clicking on a guest sets/unsets the right filters
- [x] there is a recipe page where you can see the selected intolerances

## Tasks
- [x] create toggle-button for every GuestCard
- [x] clicking on the toggle-button changes its appearance (on - off) and toggles a "selected"-property for the guest
- [x] create a recipes-page with the title "Recipes" and render the names and intolerances of all selected guests
- [x] filter double intolerances

## Size
medium
