### ISSUE TITLE
User Story 7: Show filtered recipes

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#11]
## Value statement 
As a **user** 
I want **to see filtered recipes** 
so that **I can choose one meal for all of my guests** 

## Description 
<img width="274" alt="image" src="https://user-images.githubusercontent.com/79710919/198831131-403df46c-a6b7-4fb9-a09d-5302d21352d3.png">

## Acceptance criteria
- [x] on the recipe page I can see correctly filtered recipes
- [x] there is a navbar to switch between home and recipe-page

## Tasks
- [x] create and add a component navbar (Home, Recipes) 
- [x] write a function to define the right URL for a GET-request based on the selected intolerances
- [x] fetch filtered data from the api
- [x] create RecipeCard-Component (recipe name, image, time)
- [x] render RecipeCards on the recipe-page

## Size
medium

**Comment by sebsch1337** [comment]
It's a short and easy to understand story. You might specify more the RecipeCard (will it show images / texts ?)
If the RecipeCard gets too long, you could split this in 2 stories.

**Comment by s-kond** [comment]
Hey Sebastian, thanks for your review - for now the recipe card should look like the picture in the description (name, image, time). I'll add it to the tasks :)
