### ISSUE TITLE
User Story 8: Recipe Details

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#12]
## Value statement 
As a **user** 
I want **to see more details when I click on a recipe** 
so that **I can cook the recipe**. 

## Description (Text, Scribble, Wireframe, Design)
<img width="348" alt="image" src="https://user-images.githubusercontent.com/79710919/199254490-bc2aa952-d0f0-47c3-b52a-c1b2dbeca59c.png">

## Acceptance criteria
- [ ] clicking on "More information" on a RecipeCard shows more information about that recipe (time, considered intolerances, ingredients, link to whole recipe)

## Tasks
- [ ] add a toggle-button "More information" to the RecipeCard-Component
- [ ] add the considered intolerances, time, ingredients and a link to the whole recipe (default: hidden)

## Size
medium

**Comment by sebsch1337** [comment]
The mockup looks great! It's a medium sized story - you could specify more what kind of details you want to display, in acceptance criteria and tasks. :)
