### ISSUE TITLE
Optional User Story: Transfer Details to Homepage

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#14]
## Value statement 
As a **user** 
I want **to switch pages as less as possible** 
so that **I don't get confused**. 

(Explanation: right now I have a separate UserDetails-page. I would like to delete that and implement it into the home page)

## Description (Text, Scribble, Wireframe, Design)
Before: 
![image](https://user-images.githubusercontent.com/79710919/199002481-92c6a87a-4886-4d8e-aef0-2d25b979b4ca.png)
After:
![image](https://user-images.githubusercontent.com/79710919/199002540-4f0a4e83-007f-4086-979b-93f5e7120d84.png)

## Acceptance criteria
- [ ] clicking on the three-dots-icon opens details about a guest
- [ ] clicking again closes the details
- [ ] clicking on the edit button leads you to the edit-page
- [ ] clicking on the delete button deletes the guest

## Tasks
- [ ] create a new element <MoreInfo /> with the intolerances, notes, delete-button and edit-button
- [ ] add MoreInfo to GuestCard
- [ ] add toggle-functionality to show/hide MoreInfo
- [ ] add functionality to delete-/edit-button

## Size
medium
