### ISSUE TITLE
User Story 9: Search for other recipes

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#16]
## Value statement 
As a **user** 
I want to **search for different recipes** 
so that **I can decide what I want to cook** 

## Description 
<img width="268" alt="image" src="https://user-images.githubusercontent.com/79710919/199258672-0ec7d22b-9480-414e-91e0-1bb58b27e181.png">

## Acceptance criteria
- [x] on the Recipes page you can find a searchbar
- [x] you can search for recipes by clicking on the search button

## Tasks
- [x] add a search-form (input, submit-button)
- [x] change the url for the GET-request, according to the user input
- [x] update the search results after clicking the search button

## Size
small
