### ISSUE TITLE
User Story 10: Favorite Recipes

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#17]
## Value statement - a requirement, not a solution
As a **user** 
I want **to save my favorite recipes** 
so that **I can (re-)cook them later** 

## Description (Text, Scribble, Wireframe, Design)
<img width="298" alt="image" src="https://user-images.githubusercontent.com/79710919/199261483-57fce041-8265-436b-a6db-89da105429f4.png">
<img width="259" alt="image" src="https://user-images.githubusercontent.com/79710919/199262222-b5db7362-9c7a-47d6-b86a-d30ac40ae7dd.png">

## Acceptance criteria
- [ ] Every RecipeCard has a Like-Button (heart)
- [ ] clicking on the like-button changes the button and adds the recipe to your favorites
- [ ] there is a favorites-page where you can see all your favorite recipes, filtered depending on the selected guests
- [ ] your favorite recipes are stored in LocalStorage 

## Tasks
- [ ] add a like-button with toggle-functionality to the RecipeCard-Component
- [ ] toggling the button adds/removes the recipe to a favoriteRecipesArray
- [ ] create a Favorites-Page
- [ ] render the recipes from the favoriteRecipeArray (using the RecipeCard-Component)
- [ ] make sure that also the favorite-recipes are filtered according to selected guests
- [ ] save the favoriteRecipesArray to LocalStorage 

## Size
medium
