### ISSUE TITLE
User Story 11: filter favorite recipes

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#22]
## Value statement - a requirement, not a solution
As a **user** 
I also want **to filter my favorite recipes automatically** 
so that **I see if I already have a favorite recipe for my guests** 

## Description
On the Favorites page there should be a filter-component, similar to the one in #10 
<img width="180" alt="image" src="https://user-images.githubusercontent.com/79710919/199767448-48483a46-a959-4105-a6a6-690ee5295fbb.png">

## Acceptance criteria
- [ ] on the Favorites-page, you can see the summarized intolerances from all selected guests
- [ ] you can see favorite recipes that are automatically filtered according to the selected guests

## Tasks
- [ ] render names and intolerances from selected guests on Favorites page
- [ ] filter and render favorite recipes accordingly 

## Size
small
