### ISSUE TITLE
User Story 12: more search results

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#23]
## Value statement 
As a **user** 
I want **to have access to all the search results** 
so that **I have more options** 

## Description 
![image](https://user-images.githubusercontent.com/79710919/200189324-00c87048-3253-435c-9512-7dc0cdec325a.png)

## Acceptance criteria
- [ ] after a recipe-search you see a button at the bottom of the search results to switch to show more results
 
## Tasks
- [ ] find a way to display more search results
- [ ] render the next page of results by clicking on a button

## Size
medium
