### ISSUE TITLE
User Story 13: Intolerance Information

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#24]
## Value statement - a requirement, not a solution
As a **user** 
I need **more information about the different intolerances** 
so that **I know what they mean exactly** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/79710919/200297444-05e115c2-3cf8-4b7c-86b3-4515ca1f5609.png)

## Acceptance criteria
- [ ] you can see an info-button near the navBar
- [ ] clicking on the button opens a modal with more information about the considered intolerances 

## Tasks
- [ ] add an info-button
- [ ] create a information-modal that opens when clicking on the button

## Size
medium
