### ISSUE TITLE
User Story 14: More recipe filters

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#25]
## Value statement - a requirement, not a solution
As a **user** 
I want **to have more filter options** 
so that **I can specify my search** 

## Description (Text, Scribble, Wireframe, Design)
<img width="319" alt="image" src="https://user-images.githubusercontent.com/79710919/199926116-3976ece2-12d9-4b2d-8a13-daf72a47e82a.png">

## Acceptance criteria
- [x] on the recipe page you see three dropdown filter options
- [x] meal types: breakfast, brunch, lunch/dinner, snack, teatime
- [x] dish types: bread, desserts, pasta, pizza, pastry, ...
- [x] cuisine: greek, italian, chinese, ...
- [x] on clicking submit the recipes are filtered according to the filters

## Tasks
- [x] add select-buttons to the recipe-search-form
- [x] add options with the right values
- [x] add selected filters to GET-request url on submit

## Size
large
