### ISSUE TITLE
User Story 2: Adding new guests

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#3]
## Value statement 
As a **user** 
I want to **create new guests and add them to my guest list** 
so that **I can select them later**. 

## Description (Text, Scribble, Wireframe, Design)
Home.js:
<img width="361" alt="filled guest list" src="https://user-images.githubusercontent.com/79710919/197202993-85655600-c0b4-499e-8dd0-c997490ab5a3.png">

CreateGuest.js:
<img width="304" alt="create new guest (1)" src="https://user-images.githubusercontent.com/79710919/197202561-7b0c388f-2e3a-451c-ae71-a09eb129e594.png">

## Acceptance criteria
- [x] there is an Add-Button in "Home"
- [x] clicking on the Add-Button opens a new Page with a form (CreateGuest.js)
- [x] the form-page contains a heading, a name-input, a notes-textfield and a submit-button
- [x] name input is required to create a new guest, notes are optional
- [x] clicking on the submit-button adds a new guest to the guest list and redirects you to "Home"

## Tasks
- [x] install react-router-dom
- [x] create a folder "pages" with "Home.js" and "CreateGuest.js" inside (s. scribbles)
- [x] in app.js, create Routes for "Home" and "CreateGuest"
- [x] add an Add-Button to "Home.js"
- [x] clicking on the submit-button adds a new guest (object with 'name' and 'notes') to "guestArray" (state) and redirects you to "Home"
- [x] "guestArray" is rendered in "Home" (s. scribble)

## Size
medium
