### ISSUE TITLE
backend: load dummy data

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#31]
## Value statement
As a **developer** 
I want to **load dummy data from a MongoDB** 
so that **I can remove the hard-coded testArray from my code** 

## Description
Clicking on a "load dummy data"-Button fetches and renders a guestList and a favoriteRecipeList. 

## Acceptance criteria
- [x] there is a "load dummy data"-button on home page
- [x] clicking on the button loads dummy-data from a MongoDB
- [ ] a dummy guestList and a dummy favoriteRecipeList are rendered then 

## Tasks
- [x] add a "load-dummy data"-button to home
- [x] set up a MongoDB
- [x] add dummy data to MongoDB
- [x] add button-function to load dummy data from MongoDB

## Size
medium
