### ISSUE TITLE
backend 2: loginForm

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#32]
## Value statement
As a **user** 
I want to **save and fetch my guestList and my favoriteRecipes from every device** 
so that **I can switch devices without losing my data** 

## Description (Text, Scribble, Wireframe, Design)
![image](https://user-images.githubusercontent.com/79710919/200862852-020128a6-3c3c-4ff9-91d7-771bacfb717f.png)

## Acceptance criteria
- [x] logging in with an existing username loads/renders the matching data from MongoDB
- [ ] when you're logged in and you change guests or favorite recipes a "save changes"-button appears
- [ ] clicking on "save changes", the new data is saved under that username

## Tasks
- [ ] create 2-3 dummy-user-data in MongoDB
- [ ] add login-section (see description)
- [ ] connect login-section to MongoDB

## Size
medium
