### ISSUE TITLE
backend 3: add new users

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#33]
## Value statement - a requirement, not a solution
As a **user** 
I want to **create my own username to store my guestList and favoriteRecipes** 
so that **I don't have to share 2-3 usernames with other users (#32)** 

## Description 
![image](https://user-images.githubusercontent.com/79710919/200865699-fa3fdc30-d0af-4b74-9769-261ec18e274e.png)

## Acceptance criteria
- [x] entering a new username and clicking on the "new"-button creates a new user
- [x] guestList and favoriteRecipes are empty at the beginning
- [x] after adding a new user, functionality is the same as in #32 

## Tasks
- [x] add a "new"-button to home page
- [x] validate input data (does username already exist? not too long? ...)
- [x] connect to MongoDB

## Size
medium
