### ISSUE TITLE
backend 4: delete users

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#34]
## Value statement
As a **user** 
I want **to be able to delete my username/account** 
so that **my data is deleted when I don't want to use the app anymore** 

## Description
![image](https://user-images.githubusercontent.com/79710919/200868315-66b57c5b-0126-4c74-be96-24ae15494306.png)

## Acceptance criteria
- [ ] when you're logged in, you see a "delete user"-button
- [ ] clicking on the button deletes the user and the data from MongoDB

## Tasks
- [ ] add delete-button
- [ ] connect to MongoDB

## Size
small
