### ISSUE TITLE
backend 5: addPassword

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#35]
## Value statement - a requirement, not a solution
As a **user** 
I want to **control the access to my data** 
so that **not everybody who knows my username can add/change/delete my data** 

## Description (Text, Scribble, Wireframe, Design)
A password is required for login.

## Acceptance criteria
- [ ] you have to enter the correct username/password-combination to fetch user data
- [ ] when you add a new user, you also have to set a password
 
## Tasks
- [ ] add a password-input
- [ ] validate password
- [ ] connect to MongoDB

## Size
large
