### ISSUE TITLE
User Story 3: Guest Details

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#4]
## Value statement
As a **user** 
I want **to see detailed information about my guests when I click on their name** 
so that **I can read all the information I added about them and delete them**. 

## Description (Text, Scribble, Wireframe, Design)
<img width="363" alt="guest details" src="https://user-images.githubusercontent.com/79710919/197209826-aedf2f6f-8195-44db-a8b3-67ba0d8555b6.png">
(ignore the blue edit-button in the top right corner)

## Acceptance criteria
- [x] clicking on a guests name opens a page with details about the guest
- [x] on this page, all available information are rendered 
- [x] clicking on a delete button deletes the guest 

## Tasks
- [x] create a "GuestDetails" page, which is opened when you click on a guests name and render all information about this guest (-> guestArray)
- [x] add a "back"-button that directs you to "Home"
- [x] add a "delete"-button that deletes the guest

## Size
medium
