### ISSUE TITLE
style create-/edit-page

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#41]
## Value statement - a requirement, not a solution
As a **user** 
I want **a pleasantly looking create-/edit-page** 
so that **I enjoy using the app and use it more often.** 

##Description
<img width="291" alt="image" src="https://user-images.githubusercontent.com/79710919/202155001-0a5b37ad-31a6-4ffa-bcdc-7e970d3e0db5.png">

## Acceptance criteria
- [ ] bigger input fields
- [ ] replace buttons with icons

## Tasks
- [ ] find and implement icons
- [ ] enlarge input-fields and buttons
- [ ] other small changes

## Size
small
