### ISSUE TITLE
save changes warning

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#43]
## Value statement
As a **user** 
I want **to see how many unsaved changes I have** 
so that **I get a feedback when I changed something and so that I'm reminded to save those changes.** 

## Description
<img width="145" alt="image" src="https://user-images.githubusercontent.com/79710919/202175788-febdeb15-6f88-47f6-9f7d-ef6632134657.png"> 
<img width="198" alt="image" src="https://user-images.githubusercontent.com/79710919/202176363-af30ca9f-7a69-46e9-8f51-78515947ee67.png">

## Acceptance criteria
- [ ] a small icon shows the current numer of unsaved changes
- [ ] when profile-menu is open, the icon migrates to the "save changes"-button
- [ ] when the changes are saved, the icon disappears

## Tasks
- [ ] implement a state that saves number of changes
- [ ] create and add small element to show number of changes

## Size
small
