### ISSUE TITLE
refactoring

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#45]
## Value statement - a requirement, not a solution
As a **developer** 
I need **clean code** 
so that **it's easier to read and to maintain** 

## Description
Refactor context-provider and react-modal

## Acceptance criteria
- [ ] clean up app.js 
- [ ] refactor info-modal

## Tasks
- [ ] create context-folder 
- [ ] move code from app.js to context-folder
- [ ] replace imported info-modal with own modal

## Size
medium
