### ISSUE TITLE
improve a11y

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#47]
## Value statement 
As a **user with a disability** 
I need **an app that works with assistive technologies** 
so that **I can use it without problems** 

## Description
Optimize the app for assistive technologies like screenreaders etc.

## Acceptance criteria
- [x] I can access all elements using Tab
- [x] when opening a modal, Tab focus should stay inside that modal
- [x] I can close modals with the esc-key

## Tasks
- [ ] identify possible accessibility-problems
- [ ] solve those issues

## Size
medium
