### ISSUE TITLE
User Story 4: Edit guest information

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#5]
## Value statement 
As a **user** 
I want to have a **form to edit guest-entries** 
so that **I can correct mistakes or add new information** 

## Description
<img width="399" alt="image" src="https://user-images.githubusercontent.com/79710919/197218022-ad55e2ef-0a88-44ad-84e7-e5f53725f487.png">

## Acceptance criteria
- [x] clicking on an edit button on the guests details-page opens a form where the user can edit the guests information
- [x] clicking on the submit-button updates the guests information and directs the user to the guests details-page
- [x] clicking on the back-button directs the user to the guests details-page  

## Tasks
- [x] add a edit-button to the guests detail-page (#4 )
- [x] add a "EditGuest" page with a form (s. scribble)
- [x] add the guests information as default values to the form
- [x] on submit, update the guestArray with the new information
- [x] add navigation: 'back'- and 'submit'-button lead back to the guest-details page
- [x] save data to localStorage

## Size
medium
