### ISSUE TITLE
User Story 5: Adding intolerances

### ISSUE THREAD

**Issue by s-kond** [s-kond/capstone-cook4all#6]
## Value statement 
As a **user** 
I need **the possibility to save intolerances etc. from my guests** 
so that **I don't forget them and to automatically set the recipe-filters later on**. 

## Description
CreateGuest.js (#3 ):
![image](https://user-images.githubusercontent.com/79710919/197551170-53bd12e3-6ae0-458a-b954-ef10ccb9381f.png)

EditGuest.js (#5 ):
![image](https://user-images.githubusercontent.com/79710919/197557583-9b5959fe-74d5-462b-aa0d-e7c17e1bd19e.png)

GuestDetails.js (#4 ):
![image](https://user-images.githubusercontent.com/79710919/197553048-e72c79d7-b850-41c6-849f-e2349b32ebc1.png)

## Acceptance criteria
- [x] it is possible to add intolerances on the EditGuest- and CreateGuest-pages 
- [x] possible intolerances are shown beneath the input-field
- [x] clicking on proposed intolerances adds them to an "active"-list
- [x] clicking on submit saves the intolerances for this specific guest
- [x] you see the list of intolerances on the GuestDetails-page

## Tasks
- [x] create an AddIntolerances-Component with an empty list, an input-field and an empty div for search results
- [x] create an intolerances-array with all 34 available intolerances
- [x] npm install fuzzy-search
- [x] filter the intolerances according to the user-input and render them beneath the input field (max. 3)
- [x] add proposed intolerances to an "active"-list onClick
- [x] save the intolerances for this specific guest onSubmit
- [x] render the list of intolerances on the GuestDetails-page 
- [x] implement the AddIntolerances-Component in CreateGuest.js and EditGuest.js

## Size
big
